"""initial_schema

Revision ID: 1abecc036cb8
Revises:
Create Date: 2026-07-05 20:45:35.328216

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1abecc036cb8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
